apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: lab-10-app
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672