apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: lab-10-app
type: Opaque
data:
  username: YWRtaW4= # base64 encoded "admin"
  password: YWRtaW4xMjM= # base64 encoded "admin123"